<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="aicar">
    <!-- 参数 -->
    <!-- 1.车辆尺寸 -->
    <xacro:property name="car_length" default="1.2" />
    <xacro:property name="car_width" default="0.8" />
    <xacro:property name="car_height" default="0.4" />

    <!-- 2.轮子尺寸 -->
    <xacro:property name="wheel_width" default="0.1" />
    <xacro:property name="wheel_radius" default="0.18" />

    <!-- 3.离地间隙 -->
    <xacro:property name="clearance" default="0.10" />

    <!-- 4.惯性矩阵宏 (封装好的物理公式) -->
    <!-- Box 的惯性矩阵 -->
    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <mass value="${m}" />
            <inertia
                ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0"
                iyy="${(m/12) * (w*w + d*d)}" iyz="0.0"
                izz="${(m/12) * (w*w + h*h)}" />
        </inertial>
    </xacro:macro>

    <!-- Cylinder 的惯性矩阵 -->
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia
                ixx="${(m/12) * (3*r*r + h*h)}" ixy="0.0" ixz="0.0"
                iyy="${(m/12) * (3*r*r + h*h)}" iyz="0.0"
                izz="${(m/2) * (r*r)}" />
        </inertial>
    </xacro:macro>

    <!-- 5.虚拟根节点(投影点) -->
    <link name="base_footprint" />

    <!-- 6.车身 Link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${car_length} ${car_width} ${car_height}" />
            </geometry>
            <!-- 材质颜色(可选) -->
            <material name="bule">
                <color rgba="0.1 0.1 1.0 1.0" />
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${car_length} ${car_width} ${car_height}" />
            </geometry>
        </collision>

        <xacro:box_inertia m="200.0" w="${car_width}" h="${car_height}" d="${car_length}" />
    </link>

    <!-- 7.关节:把车身驾在 Footprint 上 -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <!-- Z轴抬高: 轮子半径 + 离地间隙 -->
        <origin xyz="0.0 0.0 ${car_height/2 + clearance}" rpy="0.0 0.0 0.0" />
    </joint>

    <!-- 8.轮子宏 -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
            </visual>
            <!-- 添加碰撞属性 -->
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
            </collision>


            <xacro:cylinder_inertia m="2.0" r="${wheel_radius}" h="${wheel_width}" />
        </link>

        <!-- 添加摩擦系数 -->
        <gazebo reference="${prefix}_link">
            <!-- 摩擦系数 -->
            <mu1 value="1.0" /> <!-- 滚动方向的摩擦力(主方向) -->
            <mu2 value="0.01" /> <!-- 与滚动方向垂直的摩擦力(侧向) -->

            <!-- 接触刚度与阻尼 -->
            <kp value="10000000.0" /> <!-- 接触刚度：决定轮子有多“硬”。值越大，越不容易陷进地里 -->
            <kd value="1.0" />        <!-- 接触阻尼：决定轮子碰到地时的“弹性”。值太小，车会像蹦床一样乱跳 -->

            <!-- 摩擦力方向 -->
            <fdir1 value="1 0 0" /> <!-- 定义摩擦力的主方向。1 0 0 表示沿 X 轴 -->

            <!-- 颜色 -->
            <material>Gazebo/Black</material>  <!-- 在 Gazebo 里给轮子涂上黑色 -->
        </gazebo>

        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link" />
            <child link="${prefix}_link" />

            <!-- 
               通用位置计算公式：
               X: 车长的一半 * 系数。这里减 0.1 是为了让轮子不装在车头最顶端，稍微往里收一点(轴距)。
               Y: 车宽的一半 + 轮子宽度的一半 -> 保证轮子紧贴车身侧面，不多不少。
               Z: 轮子半径 - (离地间隙 + 车高的一半) -> 自动计算轮轴相对于车身中心的垂直偏移。
            -->
            <origin
                xyz="${x_reflect * (car_length/2 - 0.1)} ${y_reflect * (car_width/2 + wheel_width/2)} ${wheel_radius - (clearance + car_height/2)}"
                rpy="${-pi/2} 0 0" />

            <!-- 绕哪个轴转? 因为上面 rpy 已经把 Z 轴转成指向侧面了,所以这里还是绕 Z 转 -->
            <axis xyz="0 0 1" />
        </joint>
    </xacro:macro>

    <!-- 9.调用宏生成4个轮子 -->
    <xacro:wheel prefix="front_left" x_reflect="1" y_reflect="1" />
    <xacro:wheel prefix="front_right" x_reflect="1" y_reflect="-1" />
    <xacro:wheel prefix="rear_left" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="rear_right" x_reflect="-1" y_reflect="-1" />


    <!-- 10. Gazebo差速驱动插件 -->
    <gazebo>
        <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
            <!-- ROS 节点配置：定义话题名称 -->
            <ros>
                <!-- 将内部默认话题重映射为标准的 cmd_vel (控制指令) 和 odom (里程计) -->
                <remapping>cmd_vel:=cmd_vel</remapping>
                <remapping>odom:=odom</remapping>
            </ros>

            <!-- 轮子关节数量 -->
            <!-- 2 代表有两对轮子（一共4个轮子）。插件会把左侧两个绑在一起，右侧两个绑在一起 -->
            <num_wheel_pairs>2</num_wheel_pairs>

            <!-- 驱动关节配置：必须与你上面 wheel 宏生成的 joint 名字完全一致 -->
            <left_joint>front_left_joint</left_joint>
            <left_joint>rear_left_joint</left_joint> <!-- 四轮车可以写多对 -->
            <right_joint>front_right_joint</right_joint>
            <right_joint>rear_right_joint</right_joint>


            <!-- 物理尺寸：这直接影响速度计算的准确性 -->
            <!-- 轮距：左右轮子中心点的距离（计算转向的关键） -->
            <wheel_separation>${car_width + wheel_width}</wheel_separation>
            <!-- 轮子直径：计算前进速度的关键 -->
            <wheel_diameter>${2 * wheel_radius}</wheel_diameter>


            <!-- 力矩-->
            <max_wheel_torque>500</max_wheel_torque>
            <!-- 最大加速度：值越大，起步越快，但太大会导致车头“翘头”或原地打滑 -->
            <max_wheel_acceleration>1.0</max_wheel_acceleration>

            <!-- 输出 -->
            <!-- 是否发布里程计数据 (Odometry) -->
            <publish_odom>true</publish_odom>
            <!-- 是否发布从 odom 到 base_footprint 的坐标变换 (TF) -->
            <publish_odom_tf>true</publish_odom_tf>
            <!-- 是否发布轮子的坐标变换（这样 Rviz 里能看到轮子在转） -->
            <publish_wheel_tf>true</publish_wheel_tf>

            <!-- 里程计坐标系(TF)的名字。它代表机器人运动的“起始点”参考系，通常固定设为 odom -->
            <odomery_frame>odom</odomery_frame>
            <!-- 机器人的根坐标系 -->
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>
    </gazebo>
</robot>